services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: voice-assistant-ha
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - '8123:8123'
