// Generated by @nuxt/eslint on `nuxt prepare` / dev / build. It already ignores
// .nuxt and .output, so the linter only sees real source.
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt();
